// Fetch Data Actions
export const FETCH_EDUCATION = "FETCH_EDUCATION";
export const FETCH_EXPERIENCE = "FETCH_EXPERIENCE";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
//UI Content Actions
export const TOGGLE_NAVIGATION = "TOGGLE_NAVIAGTION";
// Contact Form Actions
export const CLEAR_CONTACT_FORM = "CLEAR_CONTACT_FORM";
export const EMAIL_SENT_SUCCESS = "EMAIL_SENT_SUCCESS";
export const EMAIL_SENT_FAILURE = "EMAIL_SENT_FAILURE";
export const UPDATE_COMPANY_NAME = "UPDATE_COMPANY_NAME";
export const UPDATE_EMAIL_ADDRESS = "UPDATE_EMAIL_ADDRESS";
export const UPDATE_EMAIL_MESSAGE = "UPDATE_EMAIL_MESSAGE";
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_MESSAGE_STATUS = "UPDATE_MESSAGE_STATUS";
